### ISSUE TITLE
feat: support follow for SX spaces

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/snapshot-sequencer#341]
We need to support follow ability across our different protocol and have a single API to query those. 

To do so what I propose is to add a new column "network" (with index) on the table "follows", this column will use "s" for current follows and new follows for Snapshot space, "s-tn" for Snapshot testnet, "sep" for SX-EVM on Sepolia, "sn" for Starknet mainnet and so on. This param will allow us to query network specific follows. 

We may need to change length limit on space name to be able to use a long address (like Starknet contract address which are longer than on EVM). 

We may also need to change the "follow" action to support the "network" field.

We should also expose "network" within the Snapshot hub API, and have a filter so we can query for specific network.

**Comment by wa0x6e** [comment]
Is the 25 followed spaces limit per network or global ?
